name: Rio Rita
favicon: null
layout_spectrum: 0.07483441289514303
typography_spectrum: 0.617423296906054
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.07040452398359776
  lightness: 0.6654205084778368
  saturation: 0.9701916349586099
  rhythmicContrast: 0.3637129901908338
purpose: []
