name: Rio Rita
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1379
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ee4035'
    - '#fef009'
    - '#000000'
    - '#018a60'
  brandStrength: 0.6875
  lightness: 0.6654205084778368
  saturation: 0.9701916349586099
  rhythmicContrast: 0.3637129901908338
purpose: []
